---
# - name: Create primary admin user
#   ansible.builtin.user:
#     name: sysadmin
#     groups: sudo
#     append: yes
#     shell: /bin/bash
#     create_home: yes
#   become: true

# - name: Add SSH public key for sysadmin
#   ansible.posix.authorized_key:
#     user: sysadmin
#     state: present
#     key: "{{ sysadmin_public_ssh_key }}"
#   become: true

# - name: Allow passwordless sudo to sysadmin user
#   ansible.builtin.copy:
#     dest: /etc/sudoers.d/sysadmin
#     content: "sysadmin ALL=(ALL) NOPASSWD: ALL"
#     mode: "0440"
#     validate: /usr/sbin/visudo -cf %s
#   become: true

- name: Create deployment user for CI/CD
  ansible.builtin.user:
    name: deployment
    shell: /bin/bash
    create_home: yes
  become: true

- name: Add SSH public key for deployment user
  ansible.posix.authorized_key:
    user: deployment
    state: present
    key: "{{ deployment_public_ssh_key }}"
  become: true
