---
- name: Configure sysadmin user
  ansible.builtin.import_tasks: sysadmin.yml
  when: users_setup_sysadmin | bool

- name: Configure deployment user
  ansible.builtin.import_tasks: deployment.yml
  when: users_setup_deployment | bool

# opt in to feature flags / tasks with:
# roles:
#   - role: studio.ansible.users
#     vars:
#       users_setup_deployment: true
