---
- name: Install necessary Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
  when: ansible_facts['os_family'] == "Debian" ## Debian / Ubuntu
  become: true

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create docker user for container execution
  ansible.builtin.user:
    name: docker
    state: present
    system: true
    shell: /usr/sbin/nologin
    groups: docker
    append: true
    create_home: false
  become: true

- name: Create target for docker compose
  ansible.builtin.file:
    path: /opt/docker
    state: directory
    owner: deployment
    group: deployment
    mode: "0755"
  become: true
