---
galaxy_info:
  author: Studio Vitali
  description: Installs essential system utilities on Debian.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - apt

dependencies: []
allow_duplicates: false
