---
coolify_installer_url: "https://cdn.coollabs.io/coolify/install.sh"
coolify_installer_dest: "/tmp/coolify-install.sh"
coolify_data_dir: "/data/coolify"
coolify_compose_file: "{{ coolify_data_dir }}/source/docker-compose.yml"

## Pin to a release or leave empty for latest
coolify_version: ""

## Set to false to manage upgrades manually
coolify_autoupdate: true

## All 3 needed for sucessful user creation
coolify_root_username: ""
coolify_root_user_email: ""
coolify_root_user_password: ""
